version: '3'

services:
   db:
     image: registry.cn-hangzhou.aliyuncs.com/smartnotebook/mysql:5.7.30
     privileged: true
     environment:
       MYSQL_ROOT_PASSWORD: snbSNB521
     volumes:
       - ./data_mysql:/var/lib/mysql
  
   minio:
     image: registry.cn-hangzhou.aliyuncs.com/smartnotebook/snb-minio:V1.5
     privileged: true
     environment:
       MINIO_ROOT_USER: SNB_MINIO_ADMIN
       MINIO_ROOT_PASSWORD: SnbMinio_WXY_231008
     volumes:
       - ./data_minio:/bitnami/minio/data
   
   server:
     depends_on:
       - db
       - minio
     image:  registry.cn-hangzhou.aliyuncs.com/smartnotebook/snb-server:${VERSION:-1.8.8}
     privileged: true
     volumes:
       - ./data_server/.config/server_conf_all.ini:/home/.config/server_conf.ini
       - ./wait-for-it.sh:/snb_server/wait-for-it.sh
       - ./data_server:/home
     command: ["./wait-for-it.sh", "db:3306", "--", "python", "-m", "snb_server", "--allow-root"]
     ports:
       - "${EXPOSE_PORT:-80}:8080"
    

   node:
     image:  registry.cn-hangzhou.aliyuncs.com/smartnotebook/snb-node:${VERSION:-1.8.8}
     privileged: true
     volumes:     
       - ./data_node/.config/node_conf_all.ini:/home/.config/node_conf.ini
       - ./data_node:/home
     #gpus: all 
