version: '3'

services:
   db:
     image: registry.cn-hangzhou.aliyuncs.com/smartnotebook/mysql:5.7.30
     environment:
       MYSQL_ROOT_PASSWORD: snbSNB521
     volumes:
       - ./data_mysql:/var/lib/mysql

   redis:
     image: registry.cn-hangzhou.aliyuncs.com/smartnotebook/redis:5.0.8
     command: redis-server --requirepass 5e11a0dc0699-44faf83d-5c122c1b-847b  --appendonly yes
   
   minio:
     image: registry.cn-hangzhou.aliyuncs.com/smartnotebook/smartnotebook/snb-minio:V1.5
     environment:
       MINIO_ROOT_USER: SNB_MINIO_ADMIN
       MINIO_ROOT_PASSWORD: SnbMinio_WXY_231008
     volumes:
       - ./data_minio:/bitnami/minio/data
   
   web:
     depends_on:
       - server
     image:  registry.cn-hangzhou.aliyuncs.com/smartnotebook/snb-web:1.8.6
     volumes:
       - ./snb_nginx.conf:/tmp/snb_web/nginx.conf
     ports:
       - "80:80"
   
   server:
     depends_on:
       - db
       - redis
       - minio
     image:  registry.cn-hangzhou.aliyuncs.com/smartnotebook/snb-server:1.8.6
     volumes:
       - ./server_conf.ini:/home/.config/server_conf.ini
       - ./wait-for-it.sh:/snb_server/wait-for-it.sh
       - ./data_server:/home
     command: ["./wait-for-it.sh", "db:3306", "--", "python", "-m", "snb_server", "--allow-root"]
    

   node:
     image:  registry.cn-hangzhou.aliyuncs.com/smartnotebook/snb-node:1.8.6
     volumes:
       - ./node_conf.ini:/home/.config/node_conf.ini
       - ./data_node:/home
 
